# Generated by Django 5.0 on 2025-05-27 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='allegies',
            new_name='allergies',
        ),
        migrations.RenameField(
            model_name='clientimagefile',
            old_name='customer',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='client',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='api.clientimagefile', verbose_name='Client photo'),
        ),
    ]
