# Generated by Django 5.0 on 2025-05-28 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_allegies_client_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('type', models.CharField(choices=[('initial', 'Initial Consultation'), ('follow_up', 'Follow-up'), ('emergency', 'Emergency'), ('routine', 'Routine Check-up')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.client')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='api.staff')),
            ],
            options={
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['date', 'time'], name='api_consult_date_0e8b4c_idx'), models.Index(fields=['status'], name='api_consult_status_d3b37d_idx'), models.Index(fields=['type'], name='api_consult_type_3da3ab_idx')],
            },
        ),
    ]
