# Generated by Django 5.0 on 2025-05-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='prescription',
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='api.consultation'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In-person')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='type',
            field=models.CharField(choices=[('new', 'New Consultation'), ('follow_up', 'Follow-up')], max_length=20),
        ),
    ]
