# Generated by Django 5.0 on 2025-05-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_client_contact_two_remove_staff_contact_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='mode',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('in_person', 'In-person')], default='online', max_length=20),
        ),
    ]
