# Generated by Django 5.0 on 2025-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_consultation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
