# Generated by Django 5.0 on 2025-05-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_consultation_end_date_consultation_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='consultation',
            name='api_consult_date_0e8b4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultation',
            name='api_consult_status_d3b37d_idx',
        ),
        migrations.RemoveIndex(
            model_name='consultation',
            name='api_consult_type_3da3ab_idx',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='time',
        ),
        migrations.AddField(
            model_name='consultation',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Purpose'),
        ),
    ]
