# Generated by Django 5.0 on 2025-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_consultation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='consultation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
