# Generated by Django 5.0 on 2025-05-29 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_consultation_options_consultation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='years_of_experience',
        ),
    ]
