# Generated by Django 5.0 on 2025-05-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_staff_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Years of Experience'),
        ),
    ]
