# Generated by Django 5.0 on 2025-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_consultation_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Drug Name')),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Generic Name')),
                ('brand', models.CharField(blank=True, max_length=200, null=True, verbose_name='Brand Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dosage_form', models.JSONField(blank=True, default=list, verbose_name='Dosage Form')),
                ('route', models.JSONField(blank=True, default=list, verbose_name='Route of Administration')),
                ('pharm_class', models.JSONField(blank=True, default=list, verbose_name='Pharmacologic Class')),
                ('indications', models.TextField(blank=True, help_text='What conditions this drug is used to treat', verbose_name='Indications')),
                ('side_effects', models.TextField(blank=True, verbose_name='Side Effects')),
                ('precautions', models.TextField(blank=True, verbose_name='Precautions')),
                ('active_ingredients', models.JSONField(blank=True, default=list, verbose_name='Active Ingredients')),
                ('warnings', models.TextField(blank=True, verbose_name='Warnings')),
                ('storage', models.CharField(blank=True, help_text='e.g., Store below 25°C', max_length=100, verbose_name='Storage Instructions')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='Price')),
                ('is_prescription_required', models.BooleanField(default=True, verbose_name='Prescription Required?')),
                ('image', models.ImageField(blank=True, help_text='Uploaded image of the drug', null=True, upload_to='images/drug_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
