# Generated by Django 5.0 on 2025-05-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g., tablet, capsule, bottle', max_length=50),
        ),
        migrations.CreateModel(
            name='DrugStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity in Stock')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('date_received', models.DateField(auto_now_add=True, verbose_name='Date Received')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.drug', verbose_name='Drug')),
            ],
        ),
    ]
