# Generated by Django 5.0 on 2025-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_drug_unit_drugstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='unit',
        ),
        migrations.AddField(
            model_name='drugstock',
            name='strenght',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Strenght'),
        ),
    ]
