# Generated by Django 5.0 on 2025-05-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_drug_unit_drugstock_strenght'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='image',
            new_name='img',
        ),
    ]
