# Generated by Django 5.0 on 2025-05-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_drugstock_name_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='price',
        ),
        migrations.AddField(
            model_name='drugstock',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
