# Generated by Django 5.0 on 2025-05-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_customer_order_client_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
