# Generated by Django 5.0 on 2025-05-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
    ]
