# Generated by Django 5.0 on 2025-05-31 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('diet_type', models.CharField(choices=[('regular', 'Regular'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto')], max_length=100)),
                ('duration_days', models.IntegerField(default=7)),
                ('meal_types', models.JSONField(blank=True, default=list, help_text='Describe your typical daily food intake (e.g., breakfast, lunch, dinner, snacks).', verbose_name='Dosage Form')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little to no exercise)'), ('lightly_active', 'Lightly Active (light exercise/sports 1-3 days/week)'), ('moderately_active', 'Moderately Active (moderate exercise/sports 3-5 days/week)'), ('very_active', 'Very Active (hard exercise/sports 6-7 days/week)'), ('extra_active', 'Extra Active (very hard exercise/physical job)')], default='sedentary', help_text='Your daily activity level.', max_length=20)),
                ('preferred_foods', models.TextField(blank=True, help_text='List foods you particularly enjoy (e.g., fruits, vegetables, specific cuisines).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to='api.client')),
            ],
        ),
    ]
