# Generated by Django 5.0 on 2025-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_dietplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='preferred_foods',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='goal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Diet Goal'),
        ),
    ]
