# Generated by Django 5.0 on 2025-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_dietplan_preferred_foods_dietplan_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='preferred_foods',
            field=models.JSONField(blank=True, default=list, help_text='List foods you particularly enjoy (e.g., fruits, vegetables, specific cuisines).', verbose_name='Meal Types'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='meal_types',
            field=models.JSONField(blank=True, default=list, help_text='Describe your typical daily food intake (e.g., breakfast, lunch, dinner, snacks).', verbose_name='Meal Types'),
        ),
    ]
