# Generated by Django 5.0 on 2025-05-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_dietplan_preferred_foods_alter_dietplan_meal_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='plans',
            field=models.JSONField(blank=True, default=list, verbose_name='Plans'),
        ),
    ]
