# Generated by Django 5.0 on 2025-05-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_dietplan_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='preferred_foods',
            field=models.JSONField(blank=True, default=list, help_text='List foods you particularly enjoy (e.g., fruits, vegetables, specific cuisines).', verbose_name='Preferred Foods'),
        ),
    ]
