# Generated by Django 5.0 on 2025-05-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_dietplan_preferred_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstock',
            name='img',
            field=models.ImageField(blank=True, help_text='Prescription Image', null=True, upload_to='images/drug_images/'),
        ),
    ]
