# Generated by Django 5.0 on 2025-05-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_drugstock_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstock',
            name='is_prescription_required',
            field=models.BooleanField(default=False, verbose_name='Prescription Required?'),
        ),
    ]
