# Generated by Django 5.0 on 2025-05-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_drugstock_is_prescription_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='storage',
            field=models.CharField(blank=True, help_text='e.g., Store below 25°C', max_length=250, verbose_name='Storage Instructions'),
        ),
    ]
