# Generated by Django 5.0 on 2025-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_drug_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='storage',
            field=models.CharField(blank=True, help_text='e.g., Store below 25°C', max_length=500, verbose_name='Storage Instructions'),
        ),
    ]
