# Generated by Django 5.0 on 2025-05-31 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_drug_manufacturer_alter_drug_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Manufacturer'),
        ),
    ]
